# Generated by Django 4.1 on 2022-10-02 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=300)),
                ('subject_id', models.CharField(max_length=20)),
                ('grade', models.CharField(max_length=10)),
                ('semester', models.CharField(max_length=5)),
                ('year', models.CharField(max_length=10)),
                ('curriculum', models.CharField(max_length=100)),
            ],
        ),
    ]
