# Generated by Django 4.1 on 2022-10-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.CharField(max_length=300)),
                ('subject_name_thai', models.CharField(max_length=600)),
                ('subject_name_eng', models.CharField(max_length=500)),
                ('abstract', models.CharField(max_length=3000)),
                ('subject_key', models.CharField(max_length=200)),
                ('subject_type', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=4)),
                ('subject_class', models.CharField(default='อื่นๆ', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(default='Zero', max_length=10),
        ),
    ]
