# Generated by Django 4.1 on 2022-10-07 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0002_subject_data_alter_student_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject_data',
            name='subject_type',
        ),
    ]
