# Generated by Django 3.2.16 on 2022-10-15 13:11

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0003_remove_subject_data_subject_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurpriseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('args', picklefield.fields.PickledObjectField(editable=False)),
            ],
        ),
    ]
