# Generated by Django 3.2.16 on 2023-02-18 13:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0008_auto_20230213_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=300)),
                ('curriculum', models.CharField(max_length=100)),
                ('status', models.CharField(default='ungraduate', max_length=100)),
                ('career', models.CharField(default='Zero', max_length=100)),
                ('start_year', models.CharField(default='Zero', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=300)),
                ('subject_id', models.CharField(max_length=20)),
                ('grade', models.CharField(default='Zero', max_length=10)),
                ('semester', models.CharField(max_length=5)),
                ('year', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AlterField(
            model_name='csv_file',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 18, 13, 2, 54, 855282, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='csv_file',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 18, 13, 2, 54, 855219, tzinfo=utc)),
        ),
    ]
