# Generated by Django 3.2.16 on 2023-02-19 13:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0009_auto_20230218_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_grade',
            name='curriculum',
            field=models.CharField(default='Zero', max_length=100),
        ),
        migrations.AlterField(
            model_name='csv_file',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 19, 13, 57, 9, 337576, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='csv_file',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 19, 13, 57, 9, 337515, tzinfo=utc)),
        ),
    ]
