# Generated by Django 3.2.16 on 2023-02-22 15:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0011_auto_20230219_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_data',
            name='curriculum_year',
            field=models.CharField(default='Zero', max_length=100),
        ),
        migrations.AlterField(
            model_name='csv_file',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 22, 15, 29, 42, 792111, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='csv_file',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 22, 15, 29, 42, 792021, tzinfo=utc)),
        ),
    ]
