# Generated by Django 3.2.16 on 2023-02-22 18:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0014_auto_20230222_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='surprisemodel',
            name='curriculum',
            field=models.CharField(default='Zero', max_length=100),
        ),
        migrations.AlterField(
            model_name='csv_file',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 22, 18, 32, 40, 615085, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='csv_file',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 22, 18, 32, 40, 615047, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='surprisemodel',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 22, 18, 32, 40, 614298, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='surprisemodel',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 22, 18, 32, 40, 614380, tzinfo=utc)),
        ),
    ]
