# Generated by Django 3.2.16 on 2023-02-26 12:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0015_auto_20230222_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv_file',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 26, 12, 56, 15, 951373, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='csv_file',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 26, 12, 56, 15, 951346, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='surprisemodel',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 26, 12, 56, 15, 950721, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='surprisemodel',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 26, 12, 56, 15, 950772, tzinfo=utc)),
        ),
    ]
