# Generated by Django 3.2.16 on 2023-02-26 20:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0016_auto_20230226_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='rec_model', max_length=300)),
                ('curriculum', models.CharField(default='Zero', max_length=100)),
                ('accuracy', models.CharField(default='Zero', max_length=100)),
                ('create_date', models.DateTimeField(default=datetime.datetime(2023, 2, 26, 20, 2, 17, 319075, tzinfo=utc))),
                ('update_date', models.DateTimeField(default=datetime.datetime(2023, 2, 26, 20, 2, 17, 319103, tzinfo=utc))),
                ('del_flag', models.CharField(default=0, max_length=10)),
                ('career_model', picklefield.fields.PickledObjectField(default='Zero', editable=False)),
            ],
        ),
        migrations.AlterField(
            model_name='csv_file',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 26, 20, 2, 17, 319542, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='csv_file',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 26, 20, 2, 17, 319515, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='surprisemodel',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 26, 20, 2, 17, 318358, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='surprisemodel',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 26, 20, 2, 17, 318399, tzinfo=utc)),
        ),
    ]
