# Generated by Django 3.2.16 on 2023-02-28 20:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0017_auto_20230226_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='careermodel',
            name='encode_class',
            field=picklefield.fields.PickledObjectField(default='Zero', editable=False),
        ),
        migrations.AlterField(
            model_name='careermodel',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 28, 20, 6, 39, 946837, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='careermodel',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 28, 20, 6, 39, 946866, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='csv_file',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 28, 20, 6, 39, 947452, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='csv_file',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 28, 20, 6, 39, 947422, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='surprisemodel',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 28, 20, 6, 39, 946003, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='surprisemodel',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 28, 20, 6, 39, 946050, tzinfo=utc)),
        ),
    ]
