# Generated by Django 3.2.16 on 2023-03-01 17:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0018_auto_20230228_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='careermodel',
            name='year',
            field=models.CharField(default='Zero', max_length=100),
        ),
        migrations.AddField(
            model_name='surprisemodel',
            name='year',
            field=models.CharField(default='Zero', max_length=100),
        ),
        migrations.AlterField(
            model_name='careermodel',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 1, 17, 52, 30, 80774, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='careermodel',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 1, 17, 52, 30, 80801, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='csv_file',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 1, 17, 52, 30, 81253, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='csv_file',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 1, 17, 52, 30, 81227, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='surprisemodel',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 1, 17, 52, 30, 80117, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='surprisemodel',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 1, 17, 52, 30, 80166, tzinfo=utc)),
        ),
    ]
